<?php
session_start();
include("gurii.php");

// Initialize variables for total counts
$total_positions = 0;
$total_candidates = 0;
$total_voters = 0;
$total_voted = 0;

// Fetch the required counts from the database

// Get number of positions
$query_positions = "SELECT COUNT(*) AS total_positions FROM positions"; // Assuming you have a positions table
$result_positions = mysqli_query($connect, $query_positions);
if ($result_positions) {
    $row_positions = mysqli_fetch_assoc($result_positions);
    $total_positions = $row_positions['total_positions'];
} else {
    echo "Error fetching positions count: " . mysqli_error($connect);
}

// Get number of candidates
$query_candidates = "SELECT COUNT(*) AS total_candidates FROM candidates"; // Assuming you have a candidates table
$result_candidates = mysqli_query($connect, $query_candidates);
if ($result_candidates) {
    $row_candidates = mysqli_fetch_assoc($result_candidates);
    $total_candidates = $row_candidates['total_candidates'];
} else {
    echo "Error fetching candidates count: " . mysqli_error($connect);
}

// Get total number of voters
$query_voters = "SELECT COUNT(*) AS total_voters FROM reg_user WHERE status = 1"; // Assuming the status 1 is active voters
$result_voters = mysqli_query($connect, $query_voters);
if ($result_voters) {
    $row_voters = mysqli_fetch_assoc($result_voters);
    $total_voters = $row_voters['total_voters'];
} else {
    echo "Error fetching voters count: " . mysqli_error($connect);
}

// Get the number of voters who have voted
$query_voted = "SELECT COUNT(*) AS total_voted FROM votes WHERE status = 1"; // Assuming there is a 'votes' table where status 1 means voted
$result_voted = mysqli_query($connect, $query_voted);
if ($result_voted) {
    $row_voted = mysqli_fetch_assoc($result_voted);
    $total_voted = $row_voted['total_voted'];
} else {
    echo "Error fetching voted count: " . mysqli_error($connect);
}

// Generate a new admin code and store it in session
$_SESSION['admin_code'] = rand(1000, 9999);
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Admin Dashboard - Voting System</title>
  <link rel="stylesheet" href="user interface.css">
</head>
<body>
  <div class="dashboard">
    <!-- Sidebar -->
    <div class="sidebar">
      <h2>VotingSystem</h2>
      <ul>
        <li><a href="#" class="active">Dashboard</a></li>
        <li><a href="#">Votes</a></li>
        <li><a href="#">Voters</a></li>
        <li><a href="#">Positions</a></li>
        <li><a href="#">Candidates</a></li>
        <li><a href="#">Ballot Position</a></li>
        <li><a href="#">Election Title</a></li>
      </ul>
    </div>

    <!-- Main Content -->
    <div class="main-content">
      <header>
        <h1>Dashboard</h1>
        <div class="search-bar">
          <input type="text" placeholder="Search...">
        </div>
      </header>

      <!-- Stats Cards -->
      <div class="stats">
        <div class="card">
          <h3>No. of Positions</h3>
          <p><?php echo $total_positions; ?></p>
          <a href="#">More info</a>
        </div>
        <div class="card">
          <h3>No. of Candidates</h3>
          <p><?php echo $total_candidates; ?></p>
          <a href="#">More info</a>
        </div>
        <div class="card">
          <h3>Total Voters</h3>
          <p><?php echo $total_voters; ?></p>
          <a href="#">More info</a>
        </div>
        <div class="card">
          <h3>Voters Voted</h3>
          <p><?php echo $total_voted; ?></p>
          <a href="#">More info</a>
        </div>
        <div class="card">
          <h3>Code Generated by Admin</h3>
          <p id="adminCode"><?php echo $_SESSION['admin_code']; ?></p>
          <a href="#">More info</a>
        </div>
      </div>

      <!-- Votes Tally Section -->
      <div class="votes-tally">
        <h2>Votes Tally</h2>
        <p>KB</p>
      </div>
    </div>
  </div>
</body>
</html>
