<?php
include("connection.php"); // Include your database connection file

// Start the session if needed (e.g., to store user info after successful verification)
session_start();

// Check if the form is submitted and the admin code is provided
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['adminCodeInput'])) {
    // Sanitize the input to prevent SQL injection
    $admin_code = mysqli_real_escape_string($connect, $_POST['adminCodeInput']);

    // Query to get the most recent code generated by the admin
    $query = "SELECT code FROM admin_codes ORDER BY id DESC LIMIT 1"; // Get the latest code from the table
    $result = mysqli_query($connect, $query);

    if ($result) {
        $row = mysqli_fetch_assoc($result);
        $stored_code = $row['code']; // The most recent admin code from the database

        // Compare the entered code with the stored code
        if ($admin_code == $stored_code) {
            // Code matched - perform the next action (e.g., redirect user, allow access, etc.)
            echo "<script>alert('Code verified successfully!'); window.location.href = 'dashboard.php';</script>";
        } else {
            // Code does not match
            echo "<script>alert('Incorrect code. Please try again.'); window.location.href = 'login_redirect.php';</script>";
        }
    } else {
        // Query failed (e.g., no code was generated or an error occurred)
        echo "<script>alert('Error fetching the admin code from the database.'); window.location.href = 'verify_code.html';</script>";
    }
} else {
    // Redirect back to form if the POST method is not used or if no code is provided
    header("Location: verify_code.html");
    exit();
}
?>
